#!/usr/bin/python3

import click

from s3_backup import Backup, SettingsConstructor, initialize_to_path


@click.group()
def cli():
    pass


@cli.command(help="Perform backup operation")
@click.option("--profile", help="indicate the profile to backup")
def backup(profile):
    if not profile:
        raise click.BadOptionUsage("--profile", "Must specify a profile.")

    settings = SettingsConstructor(profile_name=profile)
    profile = settings.get_profile()
    Context = settings.get_context_klass()

    with Context():
        b = Backup(profile)
        b.do_backup()

    click.echo("success")


@cli.command(help="Initialize the s3-backup CLI")
@click.option("--path", help="indicate where to store your s3-backup data")
def init(path):
    if not path:
        raise click.BadOptionUsage("--path", "Must specify a path.")

    initialize_to_path(path)
    click.echo("success")


if __name__ == "__main__":
    cli()
